### ISSUE TITLE
Transform file names to lowercase

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-dev-bundler-rollup#19]
I think it might look weird when css file is capitalized `ClassicEditor.css`. If we want to stay with this solution that `module name = file name` we can transform file name to lowercase. WDYT?

**Comment by Reinmar** [comment]
Most of the time people will like to have a file called `ckeditor.js` regardless of what's inside.

**Comment by pomek** [comment]
Probably I won't be too original but maybe `ckeditor5`? :D

**Comment by Reinmar** [comment]
I wouldn't go with `ckeditor5`. Either `ckeditor` or lowercased editor constructor. Defaulting to `ckeditor` would make writing docs simpler, but will fail if we'll allow building multiple types of editors in one directory. However, editor constructor name isn't the proper name for a bundle anyway, because you can have two bundles using two different sets of features but one editor constructor. Those would need to be generate to two different directories.

So, I'm for classic `ckeditor`. Let the directory name describe what it contains and AFAIU we allow to pass an output dir to a builder, so if you want to produce multiple builds you can have one in e.g. `vendor/ckeditor/full/` and second in `vendor/ckeditor/standard/`.

**Comment by pomek** [comment]
So, as a summary, the output path should be concatenation of:

* the output dir,
* the module name (word "editor" should be removed),
* the name: `ckeditor`.

All the path should be lowercased. 

@Reinmar, could you confirm that Am I right or rather wrong?

**Comment by Reinmar** [comment]
I think that a simple output dir + `ckeditor.*` is enough. Nothing more. If you want to build two types of editors then specify two different output dirs (I assume you can do this).

**Comment by jodator** [comment]
I've wonted to report similar issue since output `ClassicEditor.js` is ugly.
Wouldn't be better to actually provide a filename for output? I'm OK with getting always `ckeditor.js` but allowing for different filename would be nice.

**Comment by Reinmar** [comment]
I agree. If that would be useful, then let's add an option which defaults to `ckeditor.*`.

**Comment by pomek** [comment]
Ok guys, fixes are done. You can review it (#31).

**Comment by pomek** [comment]
After closing this issue, we need to update Wiki.

**Comment by pomek** [comment]
[Documentation has been updated.](https://github.com/ckeditor/ckeditor5/wiki/Development-Workflow/_compare/5fc798d17d8ad20056de4c484fde06dfd00ff926...4226476ffe9b1db7a95d8fa9a38a41b8946de78b)
